### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by leonardehrenfried** [jilen/play-circe#37]
Would you consider deploying to Maven Central?

I have helped a few projects to deploy there and am willing to help out should you need it.

Example: https://github.com/iheartradio/ficus/pull/34

**Comment by jilen** [comment]
That is great!

**Comment by leonardehrenfried** [comment]
Ok, I guess that means that you would accept a PR which adds deployment to Maven Central, right?

**Comment by jilen** [comment]
@leonardehrenfried  Yes!

**Comment by leonardehrenfried** [comment]
Are you using the release plugin for releases?

**Comment by leonardehrenfried** [comment]
And which license does this project have?

**Comment by jilen** [comment]
@leonardehrenfried  I've just add apache 2.0 LICENSE
