### ISSUE TITLE
How to use the module circe-generic-extras?

### ISSUE THREAD

**Issue by romanskie** [jilen/play-circe#43]
Hi,

I am currently running into a problem with decoding/encoding an ATD that should work as an enum attribute in one of my model case classes.

My "enum":
```
sealed trait BettingTopic
case object Bitcoin extends BettingTopic
case object Ethereum extends BettingTopic
```

my model looks like this:
```
final case class Bet(... topic: BettingTopic ...)
```

After some research I looked into circes deriveEnumerationDecoder/deriveEnumerationEncoder that comes along with the circe's "generic extras" module. This could solve my problem, but by default it is not included in play-circe. 

The necessary import would be: 
```
import io.circe.generic.extras.semiauto._
```

Is there any chance to make this work?

You can find the link to that here:
[](https://github.com/circe/circe/blob/master/modules/generic-extras/src/main/scala/io/circe/generic/extras/semiauto.scala#L37-L51)

Thank you a lot!
BG

**Comment by jilen** [comment]
@romanskie  
I think you could  add ` "io.circe" %% "circe-generic-extras" % "0.9.0"`  in your build.sbt

**Comment by romanskie** [comment]
Thank you! Works like a charm. I was not sure if mixing play-circe and io.circe dependencies is such a good idea.
