### ISSUE TITLE
2609.0 artifact issues

### ISSUE THREAD

**Issue by easel** [jilen/play-circe#44]
It appears as if the 2609.0 artifacts weren't completely rebuild - perhaps no make clean prior to publishing?

With the artifacts from maven central, I get binary incompatibility errors like this:
```
Uncaught error from thread [application-akka.actor.default-dispatcher-18]: cats.syntax.package$show$.toShowOps(Ljava/lang/Object;Lcats/Show;)Lcats/Show$Ops;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: cats.syntax.package$show$.toShowOps(Ljava/lang/Object;Lcats/Show;)Lcats/Show$Ops;
	at play.api.libs.circe.Circe.onCirceError(Circe.scala:23)
```

With the master branch built as a snapshot, everything works.

Any chance of a version bump, clean, and republish?

**Comment by jilen** [comment]
The publish process already contains `clean` step,  And the `2609.0` works fine for me. Maybe this error is caused by incompatiable cats version

**Comment by jilen** [comment]
Anyway, I've publish a new version to maven central

**Comment by easel** [comment]
Great, thanks!
