### ISSUE TITLE
Upgrade Circe version to 0.13.0

### ISSUE THREAD

**Issue by beikern** [jilen/play-circe#61]
Hi.

It would be awesome if Circe could be upgraded to 0.13.0

https://github.com/circe/circe/tree/v0.13.0

Greetings!

**Comment by pektinasen** [comment]
Fixed in #62

**Comment by pektinasen** [comment]
Thanks, so much @rodobarcaaa 

when will a new version (like `2813.0`) be published?

**Comment by zvuki** [comment]
Could someone release a version off of the latest master, so we can get 0.13.0?

cc @jilen
