### ISSUE TITLE
see faulty JSON when decode fails?

### ISSUE THREAD

**Issue by hgoldwire** [jilen/play-circe#9]
Hi peeps,

I'm blessed with very, um, fluid clients that often generate wrong JSON bodies for API requests, and I spend too much time realizing and then demonstrating this, mostly using sledgehammers like ngrep.

Circe decoder errors like "Attempt to decode value on failed cursor: El(DownField(whatever),false,false)]]" tells me what field failed but not enough about why.  I've been mucking around looking for a play-circe-friendly way to log the original request body when decoding fails, but I'm stumped.  BodyParsers seem to bail the moment they fail and I can't find a reasonable way to see the request body by composing actions, adding filters, etc.

In my dreams I glue a Logger.error of the json string onto https://github.com/jilen/play-circe/blob/master/src/main/scala/play/api/libs/circe/Circe.scala line 36 but I can't figure out how to do it short of forking the whole thing and then I lose out on mooching off your efforts.  :)  Any thoughts?  

Thanks!
- Henry

**Comment by jilen** [comment]
Two kinds of error may occurs for the currently `Circe` parse

+ Parsing illegal json by jawn [here](https://github.com/jilen/play-circe/blob/master/src/main/scala/play/api/libs/circe/Circe.scala#L60)
+ Cannot decode `Json` to  case class [here](https://github.com/jilen/play-circe/blob/master/src/main/scala/play/api/libs/circe/Circe.scala#L36)

@hgoldwire  Please feel free for forking ! And make pr if you think it will help others
